language: php
php:
  - 5.6
  - 7.0.8
  - 7.1
  - nightly

before_script:
  - travis_retry composer install --prefer-source --no-interaction --dev

script:
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN ./vendor/bin/test-reporter
